export const DEFAULT_UNIT = 'celsius';
export const WEATHER_API_URL = 'https://api.weatherapi.com/v1';
export const WEATHER_API_KEY = '';
export const EMPTY_WEATHER_TEXT = 'После поиска здесь появится карточка текущей погоды.';
export const EMPTY_FORECAST_TEXT = 'Когда город будет найден, здесь появятся карточки прогноза на 3 дня.';
export const FAVORITES_STORAGE_KEY = 'weather-assistant-favorites';
export const HISTORY_STORAGE_KEY = 'weather-assistant-history';
export const SETTINGS_STORAGE_KEY = 'weather-assistant-settings-unit';
export const HISTORY_LIMIT = 5;
